/**
 * Generate a CommonJS wrapper for the ESM module
 *
 * This creates a dist/index.cjs file that allows require() callers
 * to load the ESM module via dynamic import().
 */

import { writeFile, mkdir } from "node:fs/promises";

const wrapper = `// Auto-generated CJS wrapper for ESM module
// Load the ESM module dynamically for require() callers
// Generated by scripts/generate-cjs-wrapper.ts

async function loadModule() {
  return await import('./index.js');
}

// Synchronous export of a function that returns a promise
// This is the standard pattern for CJS wrappers around ESM
module.exports = loadModule();
`;

await mkdir("dist", { recursive: true });
await writeFile("dist/index.cjs", wrapper);
