"""PPEF type definitions."""

from .aggregate import (
    AggregatedResult,
    AggregationOutput,
    ComparisonMetrics,
    CoverageMetrics,
    SummaryStats,
)
from .case import ArtefactReference, CaseInputs, EvaluationCase, Primitive
from .claims import (
    ClaimEvaluation,
    ClaimEvaluationSummary,
    ClaimEvidence,
    ClaimStatus,
    ComparisonDirection,
    EvaluationClaim,
    ValidityScope,
)
from .evaluator import (
    ClaimsEvaluatorConfig,
    EvaluationSummary,
    EvaluationType,
    EvaluatorConfig,
    ExploratoryEvaluationSummary,
    ExploratoryEvaluatorConfig,
    MetricsCriterion,
    MetricsCriterionResult,
    MetricsEvaluationSummary,
    MetricsEvaluatorConfig,
    RobustnessEvaluatorConfig,
    ValidationResult,
)
from .perturbation import (
    PerturbationConfig,
    PerturbationType,
    RobustnessAnalysisOutput,
    RobustnessAnalysisResult,
    RobustnessMetrics,
)
from .result import (
    CorrectnessResult,
    EvaluationResult,
    Provenance,
    RankedItem,
    ResultBatch,
    ResultMetrics,
    ResultOutputs,
    RunContext,
)
from .sut import SutRegistration, SutRole

__all__ = [
    "AggregatedResult",
    "AggregationOutput",
    "ArtefactReference",
    "CaseInputs",
    "ClaimEvaluation",
    "ClaimEvaluationSummary",
    "ClaimEvidence",
    "ClaimStatus",
    "ClaimsEvaluatorConfig",
    "ComparisonDirection",
    "ComparisonMetrics",
    "CorrectnessResult",
    "CoverageMetrics",
    "EvaluationCase",
    "EvaluationClaim",
    "EvaluationResult",
    "EvaluationSummary",
    "EvaluationType",
    "EvaluatorConfig",
    "ExploratoryEvaluationSummary",
    "ExploratoryEvaluatorConfig",
    "MetricsCriterion",
    "MetricsCriterionResult",
    "MetricsEvaluationSummary",
    "MetricsEvaluatorConfig",
    "PerturbationConfig",
    "PerturbationType",
    "Primitive",
    "Provenance",
    "RankedItem",
    "ResultBatch",
    "ResultMetrics",
    "ResultOutputs",
    "RobustnessAnalysisOutput",
    "RobustnessAnalysisResult",
    "RobustnessEvaluatorConfig",
    "RobustnessMetrics",
    "RunContext",
    "SummaryStats",
    "SutRegistration",
    "SutRole",
    "ValidationResult",
    "ValidityScope",
]
